# Generated by Django 5.1 on 2024-08-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_hotel_address_alter_hotel_id_alter_hotel_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='check_in',
            new_name='check_in_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='check_out',
            new_name='check_out_date',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='number',
            new_name='room_number',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='room',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
